services:
  webserver:
    image: nginx:alpine
    depends_on:
      - app
    networks:
      - vinmo-network

  app:
    env_file:
      - .env
      - ./server/.env
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    networks:
      - vinmo-network

  queue:
    env_file:
      - .env
      - ./server/.env
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    networks:
      - vinmo-network
    depends_on:
      - app

  scheduler:
    env_file:
      - .env
      - ./server/.env
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    working_dir: /var/www
    networks:
      - vinmo-network
    depends_on:
      - app

  sse:
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    build:
      context: ./sse
      dockerfile: Dockerfile
    networks:
      - vinmo-network

volumes:
  mysql-data:
  redis-data:
  assets_volume:

networks:
  vinmo-network:
    driver: bridge