FROM node:22-alpine AS assets

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY resources ./resources
COPY vite.config.js ./
RUN npm run build

FROM nginx:alpine
COPY docker/nginx/conf.d/prod.conf /etc/nginx/conf.d/default.conf
COPY public /var/www/public
COPY --from=assets /app/public/build /var/www/public/build
