import type { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
  const appName = process.env.NEXT_PUBLIC_APP_NAME ?? "Photon";
  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://photon.org";

  return {
    title: appName,
    description: "Generated by create next app",
    alternates: {
      canonical: appUrl,
      languages: {
        "en": `${appUrl}/en`,
        "pt-BR": `${appUrl}/pt-BR`,
        "x-default": `${appUrl}/en`,
      }
    }
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children
}
